# Bu dosya, TÜİK gıda sepetini ve hibrit veri toplama stratejisi için gerekli
# API kategori adlarını ve filtreleme anahtar kelimelerini içerir.

TUIK_GIDA_SEPETI = [
    # --- Grup: Ekmek ve Tahıllar ---
    {"ana_grup_adi": "Ekmek ve Tahıllar", "madde_kodu": "0111101", "madde_adi": "Pirinç", "api_kategori_adi": "Bakliyat", "onay_kelimeleri": ["pirinç"]},
    {"ana_grup_adi": "Ekmek ve Tahıllar", "madde_kodu": "0111201", "madde_adi": "Buğday Unu", "api_kategori_adi": "Un ve İrmik", "onay_kelimeleri": ["un"]},
    {"ana_grup_adi": "Ekmek ve Tahıllar", "madde_kodu": "0111208", "madde_adi": "Bebek Sütü (Toz Karışım)", "api_kategori_adi": "Bebek Mamaları", "onay_kelimeleri": ["bebek sütü", "devam sütü", "bebek maması"]},
    {"ana_grup_adi": "Ekmek ve Tahıllar", "madde_kodu": "0111209", "madde_adi": "Bulgur", "api_kategori_adi": "Bakliyat", "onay_kelimeleri": ["bulgur"]},
    {"ana_grup_adi": "Ekmek ve Tahıllar", "madde_kodu": "0111301", "madde_adi": "Ekmek", "api_kategori_adi": "Ekmek ve Unlu Mamüller", "onay_kelimeleri": ["ekmek"]},
    {"ana_grup_adi": "Ekmek ve Tahıllar", "madde_kodu": "0111401", "madde_adi": "Bisküvi", "api_kategori_adi": "Bisküvi ve Kraker", "onay_kelimeleri": ["bisküvi", "biscolata", "probis", "saklıköy"]},
    {"ana_grup_adi": "Ekmek ve Tahıllar", "madde_kodu": "0111402", "madde_adi": "Kraker", "api_kategori_adi": "Bisküvi ve Kraker", "onay_kelimeleri": ["kraker", "çubuk", "grissini"]},
    {"ana_grup_adi": "Ekmek ve Tahıllar", "madde_kodu": "0111404", "madde_adi": "Gofret", "api_kategori_adi": "Gofret", "onay_kelimeleri": ["gofret", "hoşbeş", "canga", "dido", "çokonat", "albeni", "metro"]},
    {"ana_grup_adi": "Ekmek ve Tahıllar", "madde_kodu": "0111405", "madde_adi": "Pasta", "api_kategori_adi": "Pasta Malzemeleri", "onay_kelimeleri": ["pasta", "cheesecake", "tiramisu"]},
    {"ana_grup_adi": "Ekmek ve Tahıllar", "madde_kodu": "0111408", "madde_adi": "Kek", "api_kategori_adi": "Kek", "onay_kelimeleri": ["kek", "browni", "popkek", "dankek", "topkek", "sufle"]},
    {"ana_grup_adi": "Ekmek ve Tahıllar", "madde_kodu": "0111411", "madde_adi": "Baklava", "api_kategori_adi": "Tatlılar", "onay_kelimeleri": ["baklava"]},
    {"ana_grup_adi": "Ekmek ve Tahıllar", "madde_kodu": "0111415", "madde_adi": "Ekmek Hamuru (Yufka)", "api_kategori_adi": "Ekmek ve Unlu Mamüller", "onay_kelimeleri": ["yufka", "lavaş", "milföy"]},
    {"ana_grup_adi": "Ekmek ve Tahıllar", "madde_kodu": "0111501", "madde_adi": "Makarna", "api_kategori_adi": "Mantı Makarna ve Erişte", "onay_kelimeleri": ["makarna", "spagetti", "fettuccine", "penne"]},
    {"ana_grup_adi": "Ekmek ve Tahıllar", "madde_kodu": "0111502", "madde_adi": "Şehriye", "api_kategori_adi": "Mantı Makarna ve Erişte", "onay_kelimeleri": ["şehriye", "arpa şehriye", "tel şehriye"]},
    {"ana_grup_adi": "Ekmek ve Tahıllar", "madde_kodu": "0111602", "madde_adi": "Tahıl Gevreği", "api_kategori_adi": "Kahvaltılık Gevrek Bar ve Granola", "onay_kelimeleri": ["gevrek", "granola", "müsli", "corn flakes", "nesfit"]},

    # --- Grup: Et ve Balık ---
    {"ana_grup_adi": "Et ve Balık", "madde_kodu": "0112201", "madde_adi": "Dana Eti", "api_kategori_adi": "Kırmızı Et", "onay_kelimeleri": ["dana", "biftek", "antrikot", "bonfile", "kıyma"]},
    {"ana_grup_adi": "Et ve Balık", "madde_kodu": "0112401", "madde_adi": "Kuzu Eti", "api_kategori_adi": "Kırmızı Et", "onay_kelimeleri": ["kuzu", "pirzola", "incik"]},
    {"ana_grup_adi": "Et ve Balık", "madde_kodu": "0112501", "madde_adi": "Tavuk Eti", "api_kategori_adi": "Beyaz Et", "onay_kelimeleri": ["tavuk", "piliç", "but", "göğüs", "baget"]},
    {"ana_grup_adi": "Et ve Balık", "madde_kodu": "0112602", "madde_adi": "Sakatat", "api_kategori_adi": "Sakatat", "onay_kelimeleri": ["sakatat", "ciğer", "işkembe", "kokoreç"]},
    {"ana_grup_adi": "Et ve Balık", "madde_kodu": "0112701", "madde_adi": "Sucuk", "api_kategori_adi": "Şarküteri", "onay_kelimeleri": ["sucuk"]},
    {"ana_grup_adi": "Et ve Balık", "madde_kodu": "0112702", "madde_adi": "Sosis", "api_kategori_adi": "Şarküteri", "onay_kelimeleri": ["sosis"]},
    {"ana_grup_adi": "Et ve Balık", "madde_kodu": "0112703", "madde_adi": "Salam", "api_kategori_adi": "Şarküteri", "onay_kelimeleri": ["salam"]},
    {"ana_grup_adi": "Et ve Balık", "madde_kodu": "0112709", "madde_adi": "Hazır Et Yemekleri", "api_kategori_adi": "Hazır Gıda", "onay_kelimeleri": ["döner", "köfte"]},
    {"ana_grup_adi": "Et ve Balık", "madde_kodu": "0113101", "madde_adi": "Balık", "api_kategori_adi": "Deniz Ürünleri", "onay_kelimeleri": ["balık", "somon", "levrek", "hamsi"]},
    {"ana_grup_adi": "Et ve Balık", "madde_kodu": "0113301", "madde_adi": "Konserve Balık", "api_kategori_adi": "Deniz Ürünleri", "onay_kelimeleri": ["ton balığı", "konserve balık"]},

    # --- Grup: Süt, Peynir ve Yumurta ---
    {"ana_grup_adi": "Süt, Peynir ve Yumurta", "madde_kodu": "0114101", "madde_adi": "Süt", "api_kategori_adi": "Süt", "onay_kelimeleri": ["süt"], "yasakli_kelimeler": ["yoğurt", "peynir", "kefir", "ayran"]},
    {"ana_grup_adi": "Süt, Peynir ve Yumurta", "madde_kodu": "0114301", "madde_adi": "Yoğurt", "api_kategori_adi": "Yoğurt", "onay_kelimeleri": ["yoğurt"]},
    {"ana_grup_adi": "Süt, Peynir ve Yumurta", "madde_kodu": "0114304", "madde_adi": "Hazır Sütlü Tatlılar", "api_kategori_adi": "Tatlılar", "onay_kelimeleri": ["sütlaç", "puding", "magnolia"]},
    {"ana_grup_adi": "Süt, Peynir ve Yumurta", "madde_kodu": "0114401", "madde_adi": "Beyaz Peynir", "api_kategori_adi": "Peynir", "onay_kelimeleri": ["beyaz peynir", "süzme", "ezine"]},
    {"ana_grup_adi": "Süt, Peynir ve Yumurta", "madde_kodu": "0114402", "madde_adi": "Kaşar Peyniri", "api_kategori_adi": "Peynir", "onay_kelimeleri": ["kaşar"]},
    {"ana_grup_adi": "Süt, Peynir ve Yumurta", "madde_kodu": "0114403", "madde_adi": "Tulum Peyniri", "api_kategori_adi": "Peynir", "onay_kelimeleri": ["tulum"]},
    {"ana_grup_adi": "Süt, Peynir ve Yumurta", "madde_kodu": "0114404", "madde_adi": "Krem Peynir", "api_kategori_adi": "Peynir", "onay_kelimeleri": ["krem peynir", "labne"]},
    {"ana_grup_adi": "Süt, Peynir ve Yumurta", "madde_kodu": "0114501", "madde_adi": "Yumurta", "api_kategori_adi": "Yumurta", "onay_kelimeleri": ["yumurta"]},

    # --- Grup: Sıvı ve Katı Yağlar ---
    {"ana_grup_adi": "Sıvı ve Katı Yağlar", "madde_kodu": "0115101", "madde_adi": "Tereyağı (Kahvaltılık)", "api_kategori_adi": "Tereyağı ve Margarin", "onay_kelimeleri": ["tereyağ"]},
    {"ana_grup_adi": "Sıvı ve Katı Yağlar", "madde_kodu": "0115201", "madde_adi": "Margarin", "api_kategori_adi": "Tereyağı ve Margarin", "onay_kelimeleri": ["margarin"]},
    {"ana_grup_adi": "Sıvı ve Katı Yağlar", "madde_kodu": "0115301", "madde_adi": "Zeytinyağı", "api_kategori_adi": "Sıvı Yağlar", "onay_kelimeleri": ["zeytinyağı", "sızma"]},
    {"ana_grup_adi": "Sıvı ve Katı Yağlar", "madde_kodu": "0115302", "madde_adi": "Ayçiçek Yağı", "api_kategori_adi": "Sıvı Yağlar", "onay_kelimeleri": ["ayçiçek"]},

    # --- Grup: Meyve ve Kuruyemiş ---
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116101", "madde_adi": "Portakal", "api_kategori_adi": "Meyve", "onay_kelimeleri": ["portakal"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116102", "madde_adi": "Üzüm", "api_kategori_adi": "Meyve", "onay_kelimeleri": ["üzüm"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116105", "madde_adi": "Armut", "api_kategori_adi": "Meyve", "onay_kelimeleri": ["armut"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116107", "madde_adi": "Ayva", "api_kategori_adi": "Meyve", "onay_kelimeleri": ["ayva"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116110", "madde_adi": "Çilek", "api_kategori_adi": "Meyve", "onay_kelimeleri": ["çilek"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116112", "madde_adi": "Elma", "api_kategori_adi": "Meyve", "onay_kelimeleri": ["elma"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116121", "madde_adi": "Karpuz", "api_kategori_adi": "Meyve", "onay_kelimeleri": ["karpuz"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116122", "madde_adi": "Kavun", "api_kategori_adi": "Meyve", "onay_kelimeleri": ["kavun"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116128", "madde_adi": "Kivi", "api_kategori_adi": "Meyve", "onay_kelimeleri": ["kivi"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116130", "madde_adi": "Limon", "api_kategori_adi": "Meyve", "onay_kelimeleri": ["limon"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116131", "madde_adi": "Mandalina", "api_kategori_adi": "Meyve", "onay_kelimeleri": ["mandalina"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116134", "madde_adi": "Muz", "api_kategori_adi": "Meyve", "onay_kelimeleri": ["muz"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116135", "madde_adi": "Nar", "api_kategori_adi": "Meyve", "onay_kelimeleri": ["nar"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116137", "madde_adi": "Şeftali", "api_kategori_adi": "Meyve", "onay_kelimeleri": ["şeftali"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116201", "madde_adi": "Badem İçi", "api_kategori_adi": "Kuruyemiş ve Kuru Meyve", "onay_kelimeleri": ["badem"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116202", "madde_adi": "Ceviz İçi", "api_kategori_adi": "Kuruyemiş ve Kuru Meyve", "onay_kelimeleri": ["ceviz"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116203", "madde_adi": "Fındık İçi", "api_kategori_adi": "Kuruyemiş ve Kuru Meyve", "onay_kelimeleri": ["fındık"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116204", "madde_adi": "Antep Fıstığı", "api_kategori_adi": "Kuruyemiş ve Kuru Meyve", "onay_kelimeleri": ["antep fıstığı"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116206", "madde_adi": "Yer Fıstığı", "api_kategori_adi": "Kuruyemiş ve Kuru Meyve", "onay_kelimeleri": ["yer fıstığı"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116207", "madde_adi": "Leblebi", "api_kategori_adi": "Kuruyemiş ve Kuru Meyve", "onay_kelimeleri": ["leblebi"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116208", "madde_adi": "Ay Çekirdeği", "api_kategori_adi": "Kuruyemiş ve Kuru Meyve", "onay_kelimeleri": ["çekirdek"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116209", "madde_adi": "Kabak Çekirdeği", "api_kategori_adi": "Kuruyemiş ve Kuru Meyve", "onay_kelimeleri": ["kabak çekirdeği"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116210", "madde_adi": "Kuru Üzüm", "api_kategori_adi": "Kuruyemiş ve Kuru Meyve", "onay_kelimeleri": ["kuru üzüm"]},
    {"ana_grup_adi": "Meyve ve Kuruyemiş", "madde_kodu": "0116212", "madde_adi": "Kuru Kayısı", "api_kategori_adi": "Kuruyemiş ve Kuru Meyve", "onay_kelimeleri": ["kuru kayısı"]},

    # --- Grup: Sebze ve Bakliyat ---
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117114", "madde_adi": "Çarliston Biber", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["çarliston"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117115", "madde_adi": "Dolmalık Biber", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["dolmalık biber"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117117", "madde_adi": "Sivri Biber", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["sivri biber"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117121", "madde_adi": "Dereotu", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["dereotu"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117122", "madde_adi": "Domates", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["domates"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117125", "madde_adi": "Taze Fasulye", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["taze fasulye"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117130", "madde_adi": "Havuç", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["havuç"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117134", "madde_adi": "Ispanak", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["ıspanak"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117135", "madde_adi": "Kabak", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["kabak"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117139", "madde_adi": "Karnabahar", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["karnabahar"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117146", "madde_adi": "Kuru Soğan", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["kuru soğan"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117148", "madde_adi": "Beyaz Lahana", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["lahana"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117150", "madde_adi": "Kırmızı Lahana", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["kırmızı lahana"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117151", "madde_adi": "Mantar", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["mantar"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117152", "madde_adi": "Kıvırcık", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["kıvırcık"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117153", "madde_adi": "Maydanoz", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["maydanoz"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117155", "madde_adi": "Nane", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["nane"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117158", "madde_adi": "Patlıcan", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["patlıcan"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117160", "madde_adi": "Pırasa", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["pırasa"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117161", "madde_adi": "Roka", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["roka"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117162", "madde_adi": "Salatalık", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["salatalık"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117164", "madde_adi": "Sarımsak", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["sarımsak"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117174", "madde_adi": "Kırmızı Turp", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["turp"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117201", "madde_adi": "Patates", "api_kategori_adi": "Sebze", "onay_kelimeleri": ["patates"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117401", "madde_adi": "Kuru Fasulye", "api_kategori_adi": "Bakliyat", "onay_kelimeleri": ["kuru fasulye"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117402", "madde_adi": "Nohut", "api_kategori_adi": "Bakliyat", "onay_kelimeleri": ["nohut"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117403", "madde_adi": "Mercimek", "api_kategori_adi": "Bakliyat", "onay_kelimeleri": ["mercimek"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117501", "madde_adi": "Konserveler", "api_kategori_adi": "Konserve", "onay_kelimeleri": []}, # Genel kategori, filtre yok
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117504", "madde_adi": "Turşu", "api_kategori_adi": "Turşu", "onay_kelimeleri": ["turşu"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117505", "madde_adi": "Salça", "api_kategori_adi": "Salça", "onay_kelimeleri": ["salça"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117506", "madde_adi": "Zeytin", "api_kategori_adi": "Zeytin", "onay_kelimeleri": ["zeytin"]},
    {"ana_grup_adi": "Sebze ve Bakliyat", "madde_kodu": "0117507", "madde_adi": "Cipsler", "api_kategori_adi": "Cips", "onay_kelimeleri": ["cips", "doritos", "ruffles", "lays", "patos"]},

    # --- Grup: Şeker ve Tatlı Ürünler ---
    {"ana_grup_adi": "Şeker ve Tatlı Ürünler", "madde_kodu": "0118101", "madde_adi": "Toz Şeker", "api_kategori_adi": "Şeker ve Tatlandırıcılar", "onay_kelimeleri": ["toz şeker"]},
    {"ana_grup_adi": "Şeker ve Tatlı Ürünler", "madde_kodu": "0118102", "madde_adi": "Kesme Şeker", "api_kategori_adi": "Şeker ve Tatlandırıcılar", "onay_kelimeleri": ["kesme şeker"]},
    {"ana_grup_adi": "Şeker ve Tatlı Ürünler", "madde_kodu": "0118201", "madde_adi": "Reçel", "api_kategori_adi": "Bal ve Reçel", "onay_kelimeleri": ["reçel"]},
    {"ana_grup_adi": "Şeker ve Tatlı Ürünler", "madde_kodu": "0118203", "madde_adi": "Bal", "api_kategori_adi": "Bal ve Reçel", "onay_kelimeleri": ["bal"]},
    {"ana_grup_adi": "Şeker ve Tatlı Ürünler", "madde_kodu": "0118204", "madde_adi": "Pekmez", "api_kategori_adi": "Helva Tahin ve Pekmez", "onay_kelimeleri": ["pekmez"]},
    {"ana_grup_adi": "Şeker ve Tatlı Ürünler", "madde_kodu": "0118205", "madde_adi": "Tahin Helvası", "api_kategori_adi": "Helva Tahin ve Pekmez", "onay_kelimeleri": ["helva"]},
    {"ana_grup_adi": "Şeker ve Tatlı Ürünler", "madde_kodu": "0118206", "madde_adi": "Fındık Ezmesi", "api_kategori_adi": "Sürülebilir Ürünler ve Kahvaltılık Soslar", "onay_kelimeleri": ["fındık ezmesi"]},
    {"ana_grup_adi": "Şeker ve Tatlı Ürünler", "madde_kodu": "0118302", "madde_adi": "Çikolata Tablet", "api_kategori_adi": "Çikolata", "onay_kelimeleri": ["çikolata", "tablet", "kare"]},
    {"ana_grup_adi": "Şeker ve Tatlı Ürünler", "madde_kodu": "0118303", "madde_adi": "Çikolata Krem", "api_kategori_adi": "Sürülebilir Ürünler ve Kahvaltılık Soslar", "onay_kelimeleri": ["sürülebilir", "krem", "ezme", "nutella", "sarelle"]},
    {"ana_grup_adi": "Şeker ve Tatlı Ürünler", "madde_kodu": "0118305", "madde_adi": "Lokum", "api_kategori_adi": "Tatlılar", "onay_kelimeleri": ["lokum"]},
    {"ana_grup_adi": "Şeker ve Tatlı Ürünler", "madde_kodu": "0118311", "madde_adi": "Sakız", "api_kategori_adi": "Sakız ve Şekerleme", "onay_kelimeleri": ["sakız"]},
    {"ana_grup_adi": "Şeker ve Tatlı Ürünler", "madde_kodu": "0118312", "madde_adi": "Kağıtlı Şeker", "api_kategori_adi": "Sakız ve Şekerleme", "onay_kelimeleri": ["şekerleme", "toffe", "bonbon"]},
    {"ana_grup_adi": "Şeker ve Tatlı Ürünler", "madde_kodu": "0118401", "madde_adi": "Dondurma", "api_kategori_adi": "Dondurmalar", "onay_kelimeleri": ["dondurma"]},

    # --- Grup: Çeşitli Gıda Maddeleri ---
    {"ana_grup_adi": "Çeşitli Gıda Maddeleri", "madde_kodu": "0119001", "madde_adi": "Baharat", "api_kategori_adi": "Tuz Baharat ve Harçlar", "onay_kelimeleri": ["baharat", "nane", "kekik", "pul biber"]},
    {"ana_grup_adi": "Çeşitli Gıda Maddeleri", "madde_kodu": "0119002", "madde_adi": "Tuz", "api_kategori_adi": "Tuz Baharat ve Harçlar", "onay_kelimeleri": ["tuz"]},
    {"ana_grup_adi": "Çeşitli Gıda Maddeleri", "madde_kodu": "0119004", "madde_adi": "Kabartma Maddeleri", "api_kategori_adi": "Pasta Malzemeleri", "onay_kelimeleri": ["kabartma tozu", "vanilin"]},
    {"ana_grup_adi": "Çeşitli Gıda Maddeleri", "madde_kodu": "0119005", "madde_adi": "Sirke", "api_kategori_adi": "Ketçap Mayonez Sos ve Sirkeler", "onay_kelimeleri": ["sirke"]},
    {"ana_grup_adi": "Çeşitli Gıda Maddeleri", "madde_kodu": "0119008", "madde_adi": "Ketçap", "api_kategori_adi": "Ketçap Mayonez Sos ve Sirkeler", "onay_kelimeleri": ["ketçap"]},
    {"ana_grup_adi": "Çeşitli Gıda Maddeleri", "madde_kodu": "0119009", "madde_adi": "Mayonez", "api_kategori_adi": "Ketçap Mayonez Sos ve Sirkeler", "onay_kelimeleri": ["mayonez"]},
    {"ana_grup_adi": "Çeşitli Gıda Maddeleri", "madde_kodu": "0119012", "madde_adi": "Tahin", "api_kategori_adi": "Helva Tahin ve Pekmez", "onay_kelimeleri": ["tahin"]},
    {"ana_grup_adi": "Çeşitli Gıda Maddeleri", "madde_kodu": "0119014", "madde_adi": "Hazır Çorbalar", "api_kategori_adi": "Hazır Gıda", "onay_kelimeleri": ["hazır çorba"]},
    {"ana_grup_adi": "Çeşitli Gıda Maddeleri", "madde_kodu": "0119015", "madde_adi": "Hazır Pakette Toz Tatlılar (Puding)", "api_kategori_adi": "Tatlılar", "onay_kelimeleri": ["puding", "toz tatlı"]},

    # --- Grup: İçecekler ---
    {"ana_grup_adi": "İçecekler", "madde_kodu": "0121101", "madde_adi": "Kahve", "api_kategori_adi": "Kahve", "onay_kelimeleri": ["türk kahvesi", "filtre kahve", "çekirdek kahve"]},
    {"ana_grup_adi": "İçecekler", "madde_kodu": "0121102", "madde_adi": "Hazır Kahve", "api_kategori_adi": "Kahve", "onay_kelimeleri": ["hazır kahve", "gold", "klasik", "3ü1 arada", "2si1 arada", "nescafe"]},
    {"ana_grup_adi": "İçecekler", "madde_kodu": "0121201", "madde_adi": "Çay", "api_kategori_adi": "Çay ve Bitki Çayları", "onay_kelimeleri": ["çay", "siyah çay"]},
    {"ana_grup_adi": "İçecekler", "madde_kodu": "0121202", "madde_adi": "Bitki ve Meyve Çayı (Poşet)", "api_kategori_adi": "Çay ve Bitki Çayları", "onay_kelimeleri": ["bitki çayı", "meyve çayı", "poşet çay", "yeşil çay"]},
    {"ana_grup_adi": "İçecekler", "madde_kodu": "0121301", "madde_adi": "Kakao", "api_kategori_adi": "Kahve", "onay_kelimeleri": ["kakao"]},
    {"ana_grup_adi": "İçecekler", "madde_kodu": "0122101", "madde_adi": "Su", "api_kategori_adi": "Su", "onay_kelimeleri": ["su"]},
    {"ana_grup_adi": "İçecekler", "madde_kodu": "0122102", "madde_adi": "Maden Suyu ve Sodası", "api_kategori_adi": "Maden Suyu", "onay_kelimeleri": ["maden suyu", "soda", "mineralli"]},
    {"ana_grup_adi": "İçecekler", "madde_kodu": "0122202", "madde_adi": "Gazoz", "api_kategori_adi": "Gazlı İçecekler", "onay_kelimeleri": ["gazoz"]},
    {"ana_grup_adi": "İçecekler", "madde_kodu": "0122203", "madde_adi": "Kola", "api_kategori_adi": "Gazlı İçecekler", "onay_kelimeleri": ["kola", "coca-cola", "pepsi"]},
    {"ana_grup_adi": "İçecekler", "madde_kodu": "0122204", "madde_adi": "Soğuk Çay", "api_kategori_adi": "Gazsız İçecekler", "onay_kelimeleri": ["soğuk çay", "ice tea"]},
    {"ana_grup_adi": "İçecekler", "madde_kodu": "0122205", "madde_adi": "Ayran", "api_kategori_adi": "Ayran ve Kefir", "onay_kelimeleri": ["ayran"]},
    {"ana_grup_adi": "İçecekler", "madde_kodu": "0122301", "madde_adi": "Meyve Suyu", "api_kategori_adi": "Meyve Suyu", "onay_kelimeleri": ["meyve suyu", "nektar"]},
]